_wandb:
    value:
        cli_version: 0.22.1
        e:
            fue03tkw50aca73068f2848vu4ec4dfu:
                codePath: Take_2\preprocessing.ipynb
                codePathLocal: preprocessing.ipynb
                cpu_count: 10
                cpu_count_logical: 12
                disk:
                    /:
                        total: "187041837056"
                        used: "177325346816"
                email: 2502harshshah@gmail.com
                executable: c:\Users\2502h\anaconda3\envs\fairjob\python.exe
                git:
                    commit: ec442e0d77a938dbd2c7e27eb1457ec51481aca3
                    remote: https://github.com/harsh-shah25/fairjob_ML.git
                host: Lappy
                memory:
                    total: "16835264512"
                os: Windows-11-10.0.26100-SP0
                program: c:\Users\2502h\01_ML_Project\Take_2\preprocessing.ipynb
                python: CPython 3.12.9
                root: c:\Users\2502h\01_ML_Project\Take_2
                startedAt: "2025-10-06T15:55:22.645071Z"
                writerId: fue03tkw50aca73068f2848vu4ec4dfu
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 5
                - 6
                - 8
                - 53
            "2":
                - 5
                - 6
                - 8
                - 53
            "3":
                - 2
                - 16
            "4": 3.12.9
            "5": 0.22.1
            "8":
                - 1
                - 3
            "12": 0.22.1
            "13": windows-amd64
colsample_bytree:
    value: 0.8
eval_metric:
    value: logloss
learning_rate:
    value: 0.1
max_depth:
    value: 6
n_estimators:
    value: 200
n_jobs:
    value: -1
random_state:
    value: 42
scale_pos_weight:
    value: 142.17810048405943
subsample:
    value: 0.8
